# Generated by Django 2.0.3 on 2018-04-02 15:37

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('dialogs', '0002_auto_20180402_1535'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='answer',
            name='parent',
        ),
        migrations.AddField(
            model_name='answer',
            name='question',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='dialogs.Question'),
        ),
    ]
